# Generated by Django 5.2.1 on 2025-05-25 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('humor', models.CharField(choices=[('FELIZ', 'Feliz 😊'), ('CONTENTE', 'Contente 🙂'), ('NEUTRO', 'Neutro 😐'), ('TRISTE', 'Triste 😢'), ('ANSIOSO', 'Ansioso 😬'), ('ESTRESSADO', 'Estressado 🤯'), ('ANIMADO', 'Animado 🎉'), ('RELAXADO', 'Relaxado 😌')], default='NEUTRO', max_length=20)),
                ('sentimento_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('notas_adicionais', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_de_humor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
